# Generated by Django 3.2.6 on 2021-08-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=10)),
                ('pass_id', models.CharField(default=0, editable=False, max_length=6)),
            ],
            options={
                'verbose_name': 'Account List',
                'db_table': 'login_account',
            },
        ),
        migrations.CreateModel(
            name='applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('student_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('caste', models.CharField(max_length=30)),
                ('rd_number', models.CharField(max_length=10)),
                ('institute_type', models.CharField(max_length=20)),
                ('institute_name', models.CharField(max_length=100)),
                ('institute_address', models.CharField(max_length=255)),
                ('inst_street_address1', models.CharField(max_length=255)),
                ('inst_city', models.CharField(max_length=20)),
                ('inst_state', models.CharField(max_length=20)),
                ('inst_postal_code', models.CharField(max_length=7)),
                ('student_address', models.CharField(max_length=255)),
                ('stud_street_address1', models.CharField(max_length=255)),
                ('stud_city', models.CharField(max_length=20)),
                ('stud_state', models.CharField(max_length=20)),
                ('stud_postal_code', models.CharField(max_length=7)),
                ('course', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('adhar_number', models.CharField(max_length=12)),
                ('college_fee_amt', models.CharField(max_length=10)),
                ('from_stop', models.CharField(max_length=50)),
                ('to_stop', models.CharField(max_length=50)),
                ('via_1', models.CharField(max_length=50)),
                ('passport_size_image', models.ImageField(upload_to='photos/')),
                ('college_fees_image', models.ImageField(upload_to='photos/')),
                ('adhar_image', models.ImageField(upload_to='photos/')),
                ('study_certificate_image', models.ImageField(upload_to='photos/')),
                ('previous_marks_image', models.ImageField(upload_to='photos/')),
                ('terms_cond', models.BooleanField(default=False)),
                ('pass_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('approval', models.BooleanField(default=False)),
                ('mail_send', models.BooleanField(default=False)),
                ('expire_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Application List',
                'db_table': 'application_db',
            },
        ),
    ]
