# Generated by Django 3.2.6 on 2021-08-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=11)),
                ('messages', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Contact list',
                'db_table': 'contact_table',
            },
        ),
        migrations.CreateModel(
            name='depos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('bus_photo', models.ImageField(upload_to='bus_photos/')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'New Bus Depo',
                'db_table': 'Bus_Depos',
            },
        ),
        migrations.CreateModel(
            name='pass_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('pass_price', models.IntegerField()),
                ('processing_fee', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pass amounts list',
                'db_table': 'pass_rate_table',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_place', models.CharField(max_length=255)),
                ('To_place', models.CharField(max_length=255)),
                ('Timings', models.CharField(max_length=255)),
                ('Bus_Number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Route list',
                'db_table': 'route_table',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pass_id', models.CharField(default=0, editable=False, max_length=6)),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
    ]
