# Generated by Django 3.2.6 on 2021-08-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_contact_list_depos_pass_rate_route_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='via_1',
        ),
    ]
