# Generated by Django 3.2.5 on 2021-07-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_applicants'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('phone', models.CharField(max_length=11)),
                ('messages', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Contact list',
                'db_table': 'contact_table',
            },
        ),
    ]
