# Generated by Django 3.2.6 on 2021-08-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_applicants_via_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
