# Generated by Django 3.2.5 on 2021-07-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='pass_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('pass_price', models.IntegerField()),
                ('processing_fee', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pass amounts list',
                'db_table': 'pass_rate_table',
            },
        ),
    ]
