# Generated by Django 3.2.5 on 2021-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_pass_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='inst_postal_code',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='stud_postal_code',
            field=models.IntegerField(max_length=7),
        ),
    ]
