# Generated by Django 3.2.6 on 2021-08-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
