# Generated by Django 3.2.6 on 2021-08-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pass_id', models.CharField(default=0, editable=False, max_length=6)),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
    ]
