# Generated by Django 3.2.5 on 2021-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20210722_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='adhar_image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='college_fees_image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='passport_size_image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='previous_marks_image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='study_certificate_image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
