# Generated by Django 3.2.6 on 2021-08-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
