# Generated by Django 3.2.5 on 2021-07-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20210722_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass_rate',
            name='total_amount',
        ),
    ]
