# Generated by Django 3.2.6 on 2021-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_applicants_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='bus_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
