# Generated by Django 3.2.5 on 2021-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_remove_pass_rate_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='pass_id',
            field=models.CharField(default=0, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
