# Generated by Django 3.2.5 on 2021-07-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_applicants_pass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
