# Generated by Django 3.2.6 on 2021-09-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_alter_applicants_bus_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pass_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
