# Generated by Django 3.2.5 on 2021-07-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_auto_20210724_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
