# Generated by Django 3.2.5 on 2021-07-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_applicants_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='inst_street_address2',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='stud_street_address2',
        ),
    ]
