# Generated by Django 3.2.6 on 2021-09-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
