# Generated by Django 3.2.6 on 2021-09-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_alter_applicants_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipt/'),
        ),
    ]
