# Generated by Django 3.2.5 on 2021-07-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20210725_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pass_id',
            field=models.CharField(default=0, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
