# Generated by Django 3.2.6 on 2021-09-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_transaction_receipt_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt_pdf',
        ),
        migrations.AddField(
            model_name='applicants',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipt/'),
        ),
    ]
