# Generated by Django 3.2.6 on 2021-09-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_auto_20210901_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='pass_id',
            field=models.CharField(default=0, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='pass_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
