# Generated by Django 3.2.5 on 2021-07-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_alter_account_pass_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
