# Generated by Django 3.2.5 on 2021-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_applicants_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='mail_send',
            field=models.BooleanField(default=False),
        ),
    ]
