# Generated by Django 3.2.5 on 2021-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_applicants_mail_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp',
            field=models.CharField(default=0, editable=False, max_length=6),
        ),
    ]
